Задание 2. Добавлен README
gpb-it-factory/protasov-telegram-bot pull request #2
Opened 2024-05-08 00:22 UTC by tymillnyc

2024-05-08 05:17 UTC, vaganov-vadim requested changes
В целом всё круто, особенно понравилось грамотное использование activate/deactivate в PlantUML. Есть пара комментариев, нужно кое-что поправить.

2024-05-08 05:17 UTC, vaganov-vadim commented on README.md
> +participant User
User можно обозвать как actor, тогда он будет нарисован в виде человечка, возможно так чуть нагляднее, что это клиент :)

2024-05-08 05:17 UTC, vaganov-vadim commented on README.md
> +# Мини-Банк
Не по этому README, но в целом по репозиторию - лучше не пушить .idea, т. к. это твои локальные настройки IDEA. Разумно эту папку добавить в .gitignore.

2024-05-08 12:19 UTC, tymillnyc commented on README.md
> +# Мини-Банк
@vaganov-vadim готово

2024-05-08 12:19 UTC, tymillnyc commented on README.md
> +participant User
@vaganov-vadim готово

2024-05-14 05:40 UTC, vaganov-vadim approved these changes
Аппрув, можно вливать

2024-05-14 11:15 UTC, merged