Задание 4. Добавлен базовый CI
gpb-it-factory/protasov-telegram-bot pull request #6
Opened 2024-05-27 22:35 UTC by tymillnyc

2024-05-30 09:49 UTC, konstantin-kozlovskiy requested changes
Необходимо вернуть тест

2024-05-30 09:49 UTC, konstantin-kozlovskiy commented on src/test/java/ru/gpb/minibank/MinibankApplicationTests.java
> +//	@Test
Почему закомментирован тест?

2024-05-31 16:50 UTC, tymillnyc commented on src/test/java/ru/gpb/minibank/MinibankApplicationTests.java
> +//	@Test
В тесте я попытался воспользоваться ненастоящим токеном (через application-test.yml), но это привело к возникновению ошибки при создании бина:
Error creating bean with name 'yourTelegramBot' defined in class path resource [ru/gpb/minibank/config/BotConfig.class]: Failed to instantiate [ru.gpb.minibank.service.TelegramBot]: Factory method 'yourTelegramBot' threw exception with message: Error removing old webhook.
С моим настоящим токеном такой ошибки не возникает. Не очень понимаю, как ее исправить (кроме того, что использовать секреты в workflow). 
Сейчас раскомментировал тест, но добавил @Profile("!test") к yourTelegramBot.

2024-06-04 10:51 UTC, konstantin-kozlovskiy approved these changes

2024-06-04 11:05 UTC, merged